### ISSUE TITLE
Make IP ranges accessible

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/cf-ip-rewrite#9]
It would be great if the `$cf_ipv4` and `$cf_ipv6` where either `public static` variables, or at least have a `static` accessor to retrieve them.

Right now the only way to get my hand on the IP ranges without having `IpRewrite` change my global `REMOTE_ADDR` is this:

```php
$inst = (new \ReflectionClass(\Cloudflare\IpRewrite::class))->newInstanceWithoutConstructor();
$ref = new ReflectionClass($inst);
$ipv4 = $ref->getProperty('cf_ipv4');
$ipv6 = $ref->getProperty('cf_ipv6');
$ipv4->setAccessible(true);
$ipv6->setAccessible(true);

var_dump($ipv4->getValue($inst));
var_dump($ipv6->getValue($inst));
```

Which is rather tedious.

**Comment by thellimist** [comment]
Don't use the library to get those. 

https://www.cloudflare.com/ips/

Get it from here.

**Comment by jwineman** [comment]
We also have the Cloudflare IP addresses available from an API call:

https://api.cloudflare.com/#cloudflare-ips-cloudflare-ips

**Comment by tillkruss** [comment]
Is there a way to get notified when they change?

**Comment by jwineman** [comment]
Unfortunately we don't have any process in place to notify when the IPs change.  The reason we don't depend on that endpoint in this package though is because of how little the IPs do change.  

As long as you aren't hitting that endpoint more than like 200 times a second you should be okay polling it.

**Comment by tillkruss** [comment]
It seems silly that there is no way for the customer to know when the CF IP ranges change. Especially if you use them in something like a Nginx config: https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-
